# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.TextField(max_length=30),
        ),
    ]
