# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0004_appointment_obs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Agendamento'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Tipo de Atendimento'},
        ),
        migrations.AlterModelOptions(
            name='daysofweek',
            options={'verbose_name': 'Dias da Semana'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hour',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default='2016-01-01'),
        ),
    ]
